[build]
  command = "npm install && npm run build"
  publish = "."

# Always generate the blog at /blog on each deploy.
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npm run serve"